### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [gozzarda/CITS3002_Project#1]
Hey gozzarda!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by gozzarda** [comment]
Hey @assignguard-support!

This is indeed my work for an assignment, however, it is for one from *over seven years ago*, and for which I hold intellectual property rights. To quote UWA's copyright policy (https://www.uwa.edu.au/library/Help-and-support/Copyright-at-UWA):

> Students own the intellectual property in work that they create, unless they assign it in writing to others.

As such I have personally assessed that nothing in this repository violates anything of import or merit, and so will not be taking any action at this time.

If UWA believe me to be in violation of this policy, they are welcome to have a representative contact me in writing by the contact information they have on record for me to explain exactly how this is the case. If they can't be bothered to have a human talk to me, whatever it is can't be that important, and I certainly can't be bothered to do a robot's busywork for it. Whatever it was that resulted in your presumably automated system contacting me, please do not feel the need for it to do so again in future.

Please feel free to continue any discussion elsewhere.
Thanks!
